config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :leagues
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Required to add additional fields to Devise Controller
  # Strong Parameters

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if !user_signed_in? %>
  <!-- HOMEPAGE FOR USERS NOT SIGNED IN -->
  <%= render "shared/logged_out_homepage" %>
<% else %>
  <!-- HOMEPAGE FOR USERS SIGNED IN -->
  <%= render "shared/logged_in_homepage" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurvivorLeague</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Added to support delete method for user sign out -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>

<% if user_signed_in? %>
  <body>
<% else %>
  <body id="background-image">
<% end %>
    <!-- HEADER PARTIAL -->
    <%= render "shared/header" %>

    <!-- BODY -->
    <div class="container-fluid">
      <%= yield %>
    </div>

    <!-- FOOTER PARTIAL -->
    <%= render "shared/footer" %>

  </body>
</html>

app/views/leagues/new.html.erb
<div class="league-form">
  <h3>Create a New League</h3>
  <%= form_for :league, url: leagues_path do |f| %>
    <p>
      <%= f.text_field :league_name, placeholder: "Name Your League", class: "league-form-element" %>
    </p>
      <%= f.password_field :password, placeholder: "Password", class: "league-form-element" %>
    </p>
    <p>
      <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "league-form-element" %>
    </p>
    <%= f.submit "Create", class: "btn btn-success btn-sm league-form-element" %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-color">
  <div class="container-fluid">
    <%= link_to "NFL Survivor Pool", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-links" %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path, class: "navbar-links" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_logged_out_homepage.html.erb
<div class="centered">
  <%= link_to "Join Now", new_user_registration_path, class: "btn btn-success" %>
</div>